# Introduction

Insert introduction here...

Explain why you chose this topic, and the questions you are interested in studying. Provide context for readers who are not familiar with the topic.

(suggested length: one paragraph)


  Our motivation to choose this topic came from personal observations and the ideas discussed in the book, "Invisible Women: Exploring Data Bias in a World Designed for Men." In the book, the author, Caroline Criado Perez, uses data analysis to prove how women are affected by the patriarchy on a deeper level, how the "default male" property of the patriarchy has led to data gaps in centuries old data consequently leading to male oriented findings which are also treated as the basis for the female population. These gaps have tangible economic consequences. Women often face higher financial burdens in everyday life, from menstrual hygiene and maternity products to gender-priced essentials like razors, deodorants, and clothing that cost more despite being nearly identical to men’s versions. They also encounter hidden costs, such as paying more for safe transportation, workplace appearance expectations, or products redesigned to fit male-based standards. Healthcare adds another layer of disparity, as women frequently pay more out-of-pocket when medical systems and diagnostic tools are not designed with them in mind. These patterns motivated us to analyze large-scale U.S. datasets to quantify how these financial burdens actually differ by gender across both everyday spending and healthcare. 



-----------writing:

A.  Start early
Don’t wait to start writing. Your overall project will undoubtedly be better if you give up trying to get that last graph perfect or the last bit of analysis done and get to the writing.

  B. Interpret your graphs
All graphs should be accompanied by textual description / interpretation. Answer the question: what story does this graph tell?

  C. Be succinct 
 Your commentary should point out the most relevant trends in the context of your knowledge of the data. If a point can be made in one sentence, do not write ten sentences. Do not include irrelevant information.

  D. Tell it like it is
Be as intellectually honest as possible. That means pointing out flaws in your work, detailing obstacles, disagreements, decision points, etc. – the kinds of “behind-the-scene” things that are important but often left out of reports.

  E. Link effectively

Link to your sources; you do not need to create a reference or bibliography section.

In addition, link to your own materials that cannot be included directly in the report. Use descriptive links: “See this GitHub repo” is better than “See here.”

--------------Graphs:

Title, axis labels, tick mark labels, and legends should be comprehensible (easy to understand) and legible (easy to read / decipher).

Tick marks should not be labeled in scientific notation or with long strings of zeros, such as 3000000000. Instead, convert to smaller numbers and change the units: 3000000000 becomes “3” and the axis label “billions of views”.

Units should be intuitive (An axis labeled in month/day/year format is intuitive; one labeled in seconds since January 1, 1970 is not.)

The font size should be large enough to read clearly. The default in ggplot2 is generally too small. You can easily change it by passing the base font size to the theme, such as + theme_grey(16)  (The default base font size is 11).

The order of items on the axes and legends should be logical. (Alphabetical is usually not the best option.)

If categorical variable levels are long, set up the graph so the categorical variable is on the y-axis and the names are horizontal. A better option, if possible, is to shorten the names of the levels.

Err on the side of simplicity. Don’t, for example, overuse color when it’s not necessary. Ask yourself: does color make this graph any clearer? If it doesn’t, leave it out.

Test your graphs on nontechnical friends and family and ask for feedback.


---------------General:
- leave out glimse(), print(), head()
- dont use cat() or print() for output
- use inline code piece 
```{r}
x<-7
```

the val of `x` is `r x`.

- label including units
- no scientific notation or long labels 
- only use color when needed
- could put categorical label on y axis if needed
